:showtitle:
:doctitle: Dev-my-Ops | Kong on Kubernetes with Pulumi

=== Introduction
The quest for resilience and agility has driven us into the modern age of microservices. Bringing services to market on microservice architecture demands utilization of sprawling technology offerings and tooling. Universally this journey includes an infrastructure orchestration phase, an application deployment phase, and a service publishing phase.

In this series we will dive into using both Kong API Gateway for service publishing, and Pulumi to orchestrate our infrastructure, deploy our applications, and configure kong.

=== Tools

*Kong Gateway* is an API gateway and Ingress Controller. An API gateway is a reverse proxy that allows an organization to offer APIs as a product to internal and external clients via a centralized ingress point. An API gateway shows it’s true value when leveraged to consolidate capabilities such as authentication, session handling, rate limiting, traffic monitoring, and logging. These advanced routing features offload enforcement, maintenance, and visibility from the application teams improving their agility and consolidates this functional ownership into a central location improving global consistency and visibility.

*Pulumi* is a cloud engineering platform that brings infrastructure teams, developers, and security teams together through a unified software engineering process that accelerates innovation. The Pulumi platform and SDKs allow teams to build, deploy, and manage modern cloud applications faster and with more confidence, using any language, any architecture and any cloud. Supporting Modern Infrastructure as Code using popular programming languages including Python, JavaScript, TypeScript, Go and .NET/C#.

==== Dependencies

This article is designed for you to follow along with your Apple or Linux laptop using Kubernetes-in-Docker (kind). Before starting, please check that you have all prerequisite dependencies. +

- https://docs.docker.com/engine/reference/run[docker] (for linux) or https://www.docker.com/products/docker-desktop[docker-desktop] (for Mac)
- https://kubernetes.io/docs/reference/kubectl/kubectl[kubectl] (https://kubernetes.io/docs/tasks/tools/install-kubectl-linux[Linux] / https://kubernetes.io/docs/tasks/tools/install-kubectl-macos[Mac])
- https://kind.sigs.k8s.io[Kind]
- https://helm.sh/docs/intro/install[Helm]
- https://www.pulumi.com/docs/get-started/install/#installing-pulumi[Pulumi]
- https://docs.npmjs.com/downloading-and-installing-node-js-and-npm[npm]
- https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git client]
- https://everything.curl.dev/get[curl client]


==== Platform
Okay, now that your system is ready, let's grab the code and start our local kubernetes environment. +

. Clone the KongPulumiLabs git repo
```sh
git clone https://github.com/kong/KongPulumiLabs.git ~/kongpulumilabs && cd ~/kongpulumilabs
```
[start=2]
. Start Kubernetes-in-Docker (https://kind.sigs.k8s.io[kind]) +
```sh
docker volume create worker1
docker volume create controlplane1
kind create cluster --config ../kind/config.yml
```
[start=3]
. Verify successful Kind deploy with:
```sh
kubectl cluster-info --context kind-kong
```

[start=4]
. Write Hosts File Entries
```sh
export DATAPLANE_ADDRESS=127.0.0.1
cat <<EOF | sudo tee -a /etc/hosts
${DATAPLANE_ADDRESS}  apps.kind.home.arpa
${DATAPLANE_ADDRESS}  portal.apps.kind.home.arpa
${DATAPLANE_ADDRESS}  manager.apps.kind.home.arpa
${DATAPLANE_ADDRESS}  keycloak.apps.kind.home.arpa
EOF
```
==== Pulumi

Great! Now we have the code and a platform to deploy it to! Before we can deploy our Kong Gateway we need to initialize our Pulumi Stack. +

[start=5]
. Export your pulumi account name
```sh
# Example where my account is named "usrbinkat"
export pulumiUserName="usrbinkat"
```

[start=6]
. Deploy Kong Gateway, Cert Manager and Postgres +
```sh
npm install
pulumi stack init ${pulumiUserName}/KongPulumiLabs
pulumi stack select KongPulumiLabs
```

[start=7]
. Set Configuration Variables +
```sh
pulumi config set --secret kong:license "'{}'"
```

==== Deploy Kong Gateway
[start=8]
. Double check kubectl context & Run Pulumi Deployment +
```sh
kubectl config get-contexts --output name | grep kind-kong && pulumi up -y
```

Deploy Test Apps +

 PodInfo via pulumi
 HttpBin via pulumi

Configure Ingress(es):

 Basic ingress objects in Pulumi

=== Conclusions
In this post, we saw how to deploy a Kong Gateway, and how to deploy a test app with Pulumi. We also saw how to configure ingress objects in Pulumi.

=== Cleanup
```sh
pulumi --stack kongpulumilabs destroy -y
pulumi --stack kongpulumilabs stack rm -y
kind delete cluster --name=kong
docker volume rm worker1 controlplane1
```

=== Future Work

 Configure Kong Plugins via Pulumi
 Rate Limiting
 OIDC
 Consumers
 Token Auth
 Etc
