:showtitle:
:doctitle: Dev-my-Ops | Kong on Kubernetes with Pulumi

=== Introduction
The quest for resilience and agility has driven us into the modern age of microservices. Bringing services to market on microservice architecture demands utilization of sprawling technology offerings and tooling. Universally this journey includes an infrastructure orchestration phase, an application deployment phase, and a service publishing phase.

In this series we will dive into using both Kong API Gateway for service publishing, and Pulumi to orchestrate and orchestrate our infrastructure, deploy our applications, and configure kong.

=== Tools

Kong Gateway is an API gateway and Ingress Controller. An API gateway is a reverse proxy that allows an organization to offer APIs as a product to internal and external clients via a centralized ingress point. An API gateway shows it’s true value when leveraged to consolidate capabilities such as authentication, session handling, rate limiting, traffic monitoring, and logging. These advanced routing features offload enforcement, maintenance, and visibility from the application teams improving their agility and consolidates this functional ownership into a central location improving global consistency and visibility.

Pulumi is a cloud engineering platform that brings infrastructure teams, developers, and security teams together through a unified software engineering process that accelerates innovation. The Pulumi platform and SDKs allow teams to build, deploy, and manage modern cloud applications faster and with more confidence, using any language, any architecture and any cloud. Supporting Modern Infrastructure as Code using popular programming languages including Python, JavaScript, TypeScript, Go and .NET/C#.

=== Guide

This article is designed for you to follow along using Kubernetes-in-Docker (kind). To start, we will check that we have all of our dependency prerequisites. +

Dependencies:

- https://code.visualstudio.com[VSCode] (Optional)
- git cli / gh cli
- https://docs.docker.com/engine/reference/run[docker] (for linux) or https://www.docker.com/products/docker-desktop[docker-desktop] (for Mac)
- https://kind.sigs.k8s.io[Kind]
- https://kubernetes.io/docs/reference/kubectl/kubectl[kubectl] (https://kubernetes.io/docs/tasks/tools/install-kubectl-linux[Linux] / https://kubernetes.io/docs/tasks/tools/install-kubectl-macos[Mac])
- https://helm.sh/docs/intro/install[Helm]
- https://httpie.io/docs/cli/installation[httpie]


Okay, now that our system is ready, let's grab the code and start our local kubernetes environment. +

.Clone the KongPulumiLabs git repo
```sh
git clone https://github.com/kong/KongPulumiLabs.git ~/kongpulumilabs && cd ~/kongpulumilabs
```

.Start Kubernetes-in-Docker (https://kind.sigs.k8s.io[kind]) +
```sh
kind create cluster --config platform/kind/config.yml
```
.Verify successful Kind deploy with:
```sh
kubectl cluster-info --context kind-kongpulumilabs01
```
 Great! Now we have the code we need, and a platform to deploy it to! +

.Deploy Cert Manager and a SelfSigned ClusterIssuer +
 Before we can deploy our Kong Gateway, we need to install the cert-manager Helm chart. +
```sh
cd cert-manager
export unamePulumi='usrbinkat'
pulumi stack init ${unamePulumi}/KongPulumiLabs01
pulumi up --stack KongPulumiLabs01
```

 Pulumi Deploy Postgres +
 Pulumi Deploy Kong +
 Pulumi Publish Test App httpbin via Kong
 Pulumi Deploy Test App PodInfo via Kong

Deploy Dependencies:

 cert-manager
 postgres
 podinfo
 httpbin

Deploy Kong + Ingress Controller: (OSS Version)

 Configure variables & secrets
 Topology: Integrated (non-hybrid deploy)

Deploy Test Apps:

 PodInfo via pulumi
 HttpBin via pulumi

Configure Ingress(es):

 Basic ingress objects in Pulumi

=== Conclusions

==== Cleanup
```sh
pulumi destroy --stack KongPulumiLabs01-kongce
pulumi stack rm --stack KongPulumiLabs01-kongce
pulumi destroy --stack KongPulumiLabs01-certmanager
pulumi stack rm --stack KongPulumiLabs01-certmanager
kind delete cluster --name=kongpulumilabs01
```

Teasers for future:

 Configure Kong Plugins via Pulumi
 Rate Limiting
 OIDC
 Consumers
 Token Auth
 Etc