== Kong API Gateway on local Kind Kubernetes ==



=== Host Prep

[start=1]
. Make sure you have all link:../README.adoc#Dependencies[dependencies]

[start=2]
. Clone the TheKongLaboratory git repo
```sh
cd ~
git clone --depth 1 --branch v2.8.0 https://github.com/kong/TheKongLaboratory
cd ~/TheKongLaboratory
```

=== Pulumi Infrastructure as Code

Great! You now have: +

* [*] Installed all link:../README.adoc#Dependencies[dependencies]
* [*] Cloned https://github.com/kong/TheKongLaboratory[TheKongLaboratory] codebase.

Your system is ready to run the lab and we have the code! +
Before we can deploy our Kong Gateway we need to initialize our Pulumi codebase and configure a stack. +

[start=3]
. Pulumi local state provider login

* Set a Pulumi local state login password
* Run pulumi login --help for more state backend and login information
```sh

export PULUMI_CONFIG_PASSPHRASE=mypassword
pulumi login --local
```

[start=4]
. Initialize & Select Pulumi Stack

* Download npm packages for Pulumi typescript IaC
* Initialize and select your pulumi stack
```sh
npm install
pulumi stack init thekonglaboratory && pulumi stack select thekonglaboratory
```

[start=5]
. Set Configuration Variables +

* Create a Kong Enterprise License, an empty license will enable free mode
* Set enterprise to true if deploying with an enterprise license

```sh
pulumi config set --secret kong:license "'{}'"
pulumi config set kong:enterprise false
```

=== Deploy the Lab Platform

Now, with your prep work done, it is time to start your Kind cluster and deploy Kong to it!

[start=6]
. Deploy Kong Gateway Stack

* Start Kind Kubernetes Cluster
* Pulumi Deploy Kong Gateway & Dependencies
```sh
kind create cluster --config hack/kind/config.yml
pulumi up -y
```

[start=7]
. Go ahead and open up the Kong Manger UI !! +

* https://manager.kong.7f000001.nip.io/

== Conclusion
Now you have deployed a working Kong Gateway with Pulumi. From here you can continue with configuring kong manager and kong plugins, or you can start using the Kong Ingress Controller to publish services on your kind cluster via Kong.

== Cleanup
When you are finished with your local deployment you can destroy your kong deployment, delete the cluster, and clean up the docker volumes with the following commands +

. Unlock your local secret store.
```sh
cd ~/TheKongLaboratory
export PULUMI_CONFIG_PASSPHRASE=mypassword
pulumi login --local
```

[start=2]
. Teardown Kong Deployment & Destroy Kind Cluster.
```sh
pulumi --stack thekonglaboratory destroy -y
kind delete cluster --name=kong
```

[start=3]
. Remove Pulumi Stack, Delete cached image store, and remove cloned repository.
```sh
pulumi --stack thekonglaboratory stack rm -y
docker volume rm worker1 controlplane1
cd ~ && rm -rf ~/TheKongLaboratory
```