apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
bases:
  - "https://github.com/keycloak/keycloak-operator"
resources:
  - "selfsigned-keycloak-tls.yml"
  - "keycloak.yml"
  - "realm.yml"
  - "client.yml"
