# docker volume create worker1-containerd
# docker volume create control1-containerd
# kind create cluster --config platform/kind/config.yml

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kongpulumilabs01

networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443

nodes:

  # Control Plane Node
  - role: control-plane
    image: kindest/node:v1.23.3
    # Control-Plane Persistent image cache (optional)
    extraMounts:
    - hostPath: /var/lib/docker/volumes/control1-containerd/_data
      containerPath: /var/lib/containerd
 
  # Worker Node
  - role: worker
    image: kindest/node:v1.23.3
    # Worker Persistent image cache (optional)
    extraMounts:
      - hostPath: /var/lib/docker/volumes/worker1-containerd/_data
        containerPath: /var/lib/containerd
    # Attach our kind cluster to host ports 80 and 443
    extraPortMappings:
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 80
      containerPort: 80
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 443
      containerPort: 443
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 8080
      containerPort: 8080
    - listenAddress: "0.0.0.0"
      protocol: TCP
      hostPort: 8443
      containerPort: 8443
    # We are going to add an ingress label to this node
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
